### ISSUE TITLE
Exposed parameters not updating in .json file

### ISSUE THREAD

**Issue by taliafin1000** [disguise-one/RenderStream-UE#56]
Hi! In the latest push of the plugin, the camera names are updating but none of the variable exposed in UE seem to be updating properly in the .json file. The .json file updates when new variables are added (except for floats - booleans, integers etc. all appear fine!), but not when old variables are modified.

**Comment by chrisnashdisguise** [comment]
This should be fixed in the latest release.

**Comment by thisfox** [comment]
Hi! Just tried the plugin v6, unfortunately float variables still aren't appearing in the .json file. I also tested it in a new project with fresh variables.

**Comment by taliafin1000** [comment]
Hi! I just tried plugin v6, and float variables still don't seem to be showing up in the .json file. I also tried it in a fresh project with new plugins.

**Comment by chrisnashdisguise** [comment]
Apologies, this should now be fixed in the latest release
